List productList =[
  {
    'img':'asset/image/Orange.png',
    'name': 'Fresh Orange',
    'price': 320,
    'dis':'20%',
    'categories':'Fruits',
    'quantity':1,
  },
  {
    'img':'asset/image/kiwi.png',
    'name': 'Fresh Kiwi',
    'price': 530,
    'dis':'20%',
    'categories':'Fruits',
    'quantity':1,
  },
  {
    'img':'asset/image/Broccoli.png',
    'name': 'Brocoli',
    'price': 320,
    'dis':'28%',
    'categories':'Vegetable',
    'quantity':1,
  },
  {
    'img':'asset/image/Avocados.png',
    'name': 'Avocados',
    'price': 580,
    'dis':'28%',
    'categories':'Vegetable',
    'quantity':1,
  },
  {
    'img':'asset/image/Ghee.png',
    'name': 'Pure Ghee',
    'price': 630,
    'dis':'30%',
    'categories':'Dairy Product',
    'quantity':1,
  },
  {
    'img':'asset/image/Cheese.png',
    'name': 'Fresh Cheese',
    'price': 480,
    'dis':'30%',
    'categories':'Dairy Product',
    'quantity':1,
  },
  {
    'img':'asset/image/Strawberry.png',
    'name': 'Strawberry',
    'price': 300,
    'dis':'15%',
    'categories':'Fruits',
    'quantity':1,
  },
  {
    'img':'asset/image/Mango.png',
    'name': 'Fresh Mango',
    'price': 200,
    'dis':'28%',
    'categories':'Fruits',
    'quantity':1,
  },
  {
    'img':'asset/image/Potatoes.png',
    'name': 'Potatoes',
    'price': 70,
    'dis':'20%',
    'categories':'Vegetable',
    'quantity':1,
  },
  {
    'img':'asset/image/onion.png',
    'name': 'Onion',
    'price': 50,
    'dis':'30%',
    'categories':'Vegetable',
    'quantity':1,
  },
  {
    'img':'asset/image/Bread.png',
    'name': 'Fresh Bread',
    'price': 200,
    'dis':'30%',
    'categories':'Dairy Product',
    'quantity':1,
  },
  {
    'img':'asset/image/Butter.png',
    'name': 'Fresh Butter',
    'price': 130,
    'dis':'15%',
    'categories':'Dairy Product',
    'quantity':1,
  },
  {
    'img':'asset/image/Dragon.png',
    'name': 'Fresh Dragonfruit',
    'price': 500,
    'dis':'28%',
    'categories':'Fruits',
    'quantity':1,
  },
  {
    'img':'asset/image/Apple.png',
    'name': 'Fresh Apple',
    'price': 200,
    'dis':'28%',
    'categories':'Fruits',
    'quantity':1,
  },
  {
    'img':'asset/image/Ladyfinger.png',
    'name': 'Ladyfinger',
    'price': 100,
    'dis':'20%',
    'categories':'Vegetable',
    'quantity':1,
  },
  {
    'img':'asset/image/Tomato.png',
    'name': 'Tomato',
    'price': 50,
    'dis':'20%',
    'categories':'Vegetable',
    'quantity':1,
  },
  {
    'img':'asset/image/Paneer.png',
    'name': 'Fresh Paneer',
    'price': 500,
    'dis':'30%',
    'categories':'Dairy Product',
    'quantity':1,
  },
  {
    'img':'asset/image/Milk.png',
    'name': 'Fresh Milk',
    'price': 200,
    'dis':'30%',
    'categories':'Dairy Product',
    'quantity':1,
  },

];


List cartList = [];